// ══════════════════════════════════════════════════
// Models/Attendance.cs
// Represents one check-in record stored in the DB
// ══════════════════════════════════════════════════
using System;

namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single attendance check-in record.
    /// Maps directly to the Attendance table in the database.
    /// Also holds extra display fields populated via SQL JOIN queries.
    /// </summary>
    public class Attendance
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this attendance record.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int AttendanceID { get; set; }


        // ─────────────────────────────────────────────
        //  Foreign Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// The ID of the member who checked in.
        /// Links to the MemberID primary key in the Members table.
        /// </summary>
        public int MemberID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// The exact date and time the member checked in.
        /// Set automatically to the current timestamp when attendance is marked.
        /// </summary>
        public DateTime CheckInTime { get; set; }


        // ─────────────────────────────────────────────
        //  JOIN / Display Fields
        //  Not stored in the Attendance table —
        //  populated by SQL JOIN with the Members table.
        // ─────────────────────────────────────────────

        /// <summary>
        /// The full name of the member who checked in.
        /// Retrieved via JOIN on the Members table for display purposes.
        /// </summary>
        public string MemberName { get; set; }

        /// <summary>
        /// The phone number of the member who checked in.
        /// Retrieved via JOIN on the Members table for display purposes.
        /// </summary>
        public string Phone { get; set; }
    }
}