// ══════════════════════════════════════════════════
// Models/MembershipPlan.cs
// Represents one membership plan (Monthly, Quarterly, Yearly)
// ══════════════════════════════════════════════════
namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single membership plan offered by the gym.
    /// Maps directly to the MembershipPlans table in the database.
    /// Used in MembershipForm to populate the plan dropdown and
    /// calculate subscription end dates.
    /// </summary>
    public class MembershipPlan
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this membership plan.
        /// Auto-generated by the database on insert.
        /// Used as the hidden ValueMember in the plan dropdown.
        /// </summary>
        public int PlanID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// Display name of the membership plan.
        /// Examples: "Monthly", "Quarterly", "Yearly".
        /// Shown as the visible text in the plan dropdown (DisplayMember).
        /// </summary>
        public string PlanName { get; set; }

        /// <summary>
        /// Duration of the plan expressed in total days.
        /// Used to auto-calculate the subscription end date:
        /// EndDate = StartDate + DurationDays.
        /// Examples: 30 (Monthly), 90 (Quarterly), 365 (Yearly).
        /// </summary>
        public int DurationDays { get; set; }

        /// <summary>
        /// Cost of the membership plan in Pakistani Rupees (Rs.).
        /// Displayed in the plan details label in MembershipForm
        /// and shown in the Reports form payment summary.
        /// </summary>
        public decimal Price { get; set; }
    }
}