// ══════════════════════════════════════════════════
// Models/MemberMembership.cs
// Represents a subscription assigned to a member
// ══════════════════════════════════════════════════
using System;

namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single membership subscription
    /// assigned to a gym member.
    /// Maps directly to the MemberMemberships table in the database.
    /// Also holds extra display fields populated via SQL JOIN queries.
    /// </summary>
    public class MemberMembership
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this subscription record.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int SubID { get; set; }


        // ─────────────────────────────────────────────
        //  Foreign Keys
        // ─────────────────────────────────────────────

        /// <summary>
        /// The ID of the member this subscription belongs to.
        /// Links to the MemberID primary key in the Members table.
        /// </summary>
        public int MemberID { get; set; }

        /// <summary>
        /// The ID of the membership plan assigned to this subscription.
        /// Links to the PlanID primary key in the MembershipPlans table.
        /// </summary>
        public int PlanID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// The date the membership subscription starts.
        /// Set by the user via the date picker in MembershipForm.
        /// </summary>
        public DateTime StartDate { get; set; }

        /// <summary>
        /// The date the membership subscription expires.
        /// Calculated automatically as StartDate + plan duration in days.
        /// </summary>
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Current status of the subscription.
        /// Typical values: "Active", "Expired", or "Cancelled".
        /// Updated when a membership is cancelled or renewed.
        /// </summary>
        public string Status { get; set; }


        // ─────────────────────────────────────────────
        //  JOIN / Display Fields
        //  Not stored in the MemberMemberships table —
        //  populated by SQL JOIN with Members and Plans tables.
        // ─────────────────────────────────────────────

        /// <summary>
        /// Full name of the member holding this subscription.
        /// Retrieved via JOIN on the Members table for display purposes.
        /// </summary>
        public string MemberName { get; set; }

        /// <summary>
        /// Name of the membership plan assigned to this subscription.
        /// Retrieved via JOIN on the MembershipPlans table for display purposes.
        /// </summary>
        public string PlanName { get; set; }

        /// <summary>
        /// Price of the assigned membership plan.
        /// Retrieved via JOIN on the MembershipPlans table for display purposes.
        /// </summary>
        public decimal P { get; set; }

        /// <summary>
        /// Number of days remaining until the subscription expires.
        /// Calculated in the SQL query as the difference between
        /// EndDate and today's date. Used in the expiring memberships report
        /// to highlight urgent renewals (7 or fewer days left).
        /// </summary>
        public int DaysLeft { get; set; }
    }
}