// ══════════════════════════════════════════════════
// Models/Member.cs
// Represents one gym member
// ══════════════════════════════════════════════════
using System;

namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single gym member.
    /// Maps directly to the Members table in the database.
    /// Used across MemberForm, AttendanceForm, and MembershipForm.
    /// </summary>
    public class Member
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this member.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int MemberID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// Full name of the member (first + last).
        /// Required field — cannot be empty on save.
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// Contact phone number of the member.
        /// Required field — cannot be empty on save.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Email address of the member.
        /// Optional field — may be left blank.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Gender of the member (e.g. "Male" or "Female").
        /// Selected from a dropdown in MemberForm.
        /// </summary>
        public string Gender { get; set; }

        /// <summary>
        /// The date the member joined the gym.
        /// Defaults to today's date when adding a new member.
        /// </summary>
        public DateTime JoinDate { get; set; }


        // ─────────────────────────────────────────────
        //  Status Field
        // ─────────────────────────────────────────────

        /// <summary>
        /// Indicates whether the member's account is currently active.
        /// True = Active, False = Inactive.
        /// Maps to the Status dropdown (index 0 = Active) in MemberForm.
        /// Only active members appear in attendance and membership dropdowns.
        /// </summary>
        public bool IsActive { get; set; }
    }
}