// ══════════════════════════════════════════════════
// Models/Payment.cs
// Represents one payment transaction
// ══════════════════════════════════════════════════
using System;

namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single payment transaction made by a member.
    /// Maps directly to the Payments table in the database.
    /// Used in PaymentForm for saving, deleting, and displaying payment records.
    /// Also holds an extra display field populated via SQL JOIN queries.
    /// </summary>
    public class Payment
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this payment transaction.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int PaymentID { get; set; }


        // ─────────────────────────────────────────────
        //  Foreign Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// The ID of the member who made this payment.
        /// Links to the MemberID primary key in the Members table.
        /// </summary>
        public int MemberID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// The payment amount in Pakistani Rupees (Rs.).
        /// Must be a positive value — validated in PaymentForm before saving.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// The date the payment was recorded.
        /// Defaults to today's date via the date picker in PaymentForm.
        /// </summary>
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// The method used to make the payment.
        /// Examples: "Cash", "Card", "Online Transfer".
        /// Selected from a dropdown in PaymentForm.
        /// </summary>
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Optional notes or remarks about this payment.
        /// Can be used to record context such as "Membership renewal"
        /// or "Partial payment". May be left blank.
        /// </summary>
        public string Notes { get; set; }


        // ─────────────────────────────────────────────
        //  JOIN / Display Field
        //  Not stored in the Payments table —
        //  populated by SQL JOIN with the Members table.
        // ─────────────────────────────────────────────

        /// <summary>
        /// Full name of the member who made this payment.
        /// Retrieved via JOIN on the Members table for display purposes.
        /// Shown in the payments grid and search results in PaymentForm.
        /// </summary>
        public string MemberName { get; set; }
    }
}