// ══════════════════════════════════════════════════
// Models/Trainer.cs
// Represents one gym trainer
// ══════════════════════════════════════════════════
namespace Gym_Management_System.Models
{
    /// <summary>
    /// Model class representing a single gym trainer.
    /// Maps directly to the Trainers table in the database.
    /// Used in TrainerForm for adding, updating, deleting,
    /// and displaying trainer records.
    /// </summary>
    public class Trainer
    {
        // ─────────────────────────────────────────────
        //  Primary Key
        // ─────────────────────────────────────────────

        /// <summary>
        /// Unique identifier for this trainer.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int TrainerID { get; set; }


        // ─────────────────────────────────────────────
        //  Core Fields
        // ─────────────────────────────────────────────

        /// <summary>
        /// Full name of the trainer (first + last).
        /// Required field — cannot be empty on save.
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// Contact phone number of the trainer.
        /// Required field — cannot be empty on save.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// The trainer's area of expertise or specialization.
        /// Examples: "Cardio", "Weight Training", "Yoga", "Boxing".
        /// Optional field — may be left blank.
        /// </summary>
        public string Specialty { get; set; }

        /// <summary>
        /// Monthly salary of the trainer in Pakistani Rupees (Rs.).
        /// Optional field — defaults to 0 if left blank in TrainerForm.
        /// </summary>
        public decimal Salary { get; set; }


        // ─────────────────────────────────────────────
        //  Status Field
        // ─────────────────────────────────────────────

        /// <summary>
        /// Indicates whether the trainer is currently active.
        /// True = Active, False = Inactive.
        /// Maps to the Status dropdown (index 0 = Active) in TrainerForm.
        /// </summary>
        public bool IsActive { get; set; }
    }
}